version: "3.2"
services:
  ubuntu-texlive-ja:
    container_name: texlive-ja
    #image: korosuke613/ubuntu-texlive-ja-devcontainer
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/root/.gitconfig
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"